export {
  ScissorsIcon,
  HairTreatmentIcon,
  GroomingIcon,
  BeautyCareIcon,
  NailsIcon,
  SpaIcon,
  BridalIcon,
  AcademyIcon,
  PiercingIcon,
  StarIcon,
  StarHalfIcon,
  PlayIcon,
  PhoneIcon,
  ClockIcon,
  MapPinIcon,
  InstagramIcon,
  MenuIcon,
  CloseIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  GoogleIcon,
} from "./icon-definitions";
